Restrict passphrases
Zondax/ledger-arweave pull request #73
Opened 2022-07-13 13:45 UTC by chcmedeiros

2022-07-13 18:54 UTC, jleni requested changes

2022-07-13 18:54 UTC, jleni commented on app/src/apdu_handler.c
> +        view_review_show(0x03);
what is the meaning of 0x03?
Can we add some DEFINES in zxlib so the meaning is more clear?

2022-07-13 18:54 UTC, jleni commented on app/src/apdu_handler.c
> +    view_review_show(0x03);
same here

2022-07-13 19:02 UTC, jleni commented
Awesome work @chcmedeiros !

2022-07-19 17:42 UTC, ftheirs approved these changes

2022-07-19 17:44 UTC, merged